### ISSUE TITLE
Add 4 new plans (GND, thurgood marshall,etc)

### ISSUE THREAD

**Issue by tpfaff** [tpfaff/Bernie2020#30]

**Comment by tpfaff** [comment]
Hey @GarrettShorr  anything I can do to help you here?

**Comment by GarrettShorr** [comment]
I'm in the middle of adding the Green New Deal so those categories and links aren't complete yet, but we should be good to go on the spreadsheet with the Thurgood Marshall Plan and the Workplace Democracy Plan. If you could help convert those to json, I could finish parsing up the Green New Deal, cancel medical debt, and fix journalism stuff tonight.

**Comment by GarrettShorr** [comment]
Plans have been added. Waiting on a code review on the changes to plan retrieval and categorization.

Should we remove the existing plans that have been overridden by the new detailed ones? For instance, there are some existing green new deal ones when it was just a vague concept and not specific.

**Comment by GarrettShorr** [comment]
Done
