### ISSUE TITLE
When timeline image view holders get rebound, they are the wrong size.

### ISSUE THREAD

**Issue by tpfaff** [tpfaff/Bernie2020#36]
The previous image size is used for newly bound images. It looks weird.

**Comment by MikeL1B0** [comment]
I had to change TimelineItem to include another field (image_resource), In TimelineFragment I added ImageDescriptionViewHolder2 which included another input in bind to take in (image_resource),  and I had to change timeline.json to include the image names, also the images files were added to drawable.  

To make sure the images looked about right the timeline_image_viewholder.xml had the following two lines added to ImageView:  
 android:adjustViewBounds="true"
 android:scaleType="fitCenter"


[timeline_changes.zip](https://github.com/tpfaff/Bernie2020/files/3564472/timeline_changes.zip)
